sudo: required

services:
  - docker
  
script:
 - docker pull firilith/docker-tectonic
 - docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind firilith/docker-tectonic /bin/sh -c "tectonic --keep-intermediates --reruns 0 bachproef/bachproef-tin.tex; biber bachproef/bachproef-tin; tectonic bachproef/bachproef-tin.tex"
 - docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind firilith/docker-tectonic /bin/sh -c "tectonic --keep-intermediates --reruns 0 voorstel/mertens_lennert_voorstel.tex; biber voorstel/mertens_lennert_voorstel; tectonic voorstel/mertens_lennert_voorstel.tex"
 - docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind firilith/docker-tectonic /bin/sh -c "tectonic poster/conference_poster.tex"
